//Message data schema
const chatRoomMessagesData = {
    name: "chat_room_msgs_data",
    primarykey: "TMESSAGES_Message_ID",
    properties: {
        TMESSAGES_Message_ID: "int",
        TMESSAGES_Record_Today_First_message: "int",
        TMESSAGES_Content: { type: "string", default: null },
        TMESSAGES_Document_ID: {type: "int", default: null, optional:true},
        TMESSAGES_Chat_Room_ID: {type: "int", default: null},
        TMESSAGES_File_Name: {type: "string", default: null, optional:true},
        TMESSAGES_File_Type: {type: "string", default: null},
        TMESSAGES_Thumbnail_Url: {type: "string", default: null, optional:true},
        TMESSAGES_IS_User_Join: {type: "int", default: 0},
        TMESSAGES_UID: {type: "string", default: null},
        TMESSAGES_Created_On: {type: "date", default: null},
        TMESSAGES_IS_User_Exit: {type: "int", default: 0},
        TMESSAGES_IS_Reply: {type: "int", default: 0},
        TMESSAGES_Reply_ID: {type: "int", default: 0, optional:true},
        TMESSAGES_Reply_File_Type: {type: "string", default: null, optional:true},
        TMESSAGES_Reply_contand: {type: "string", default: null, optional:true},
        TMESSAGES_Read_Status: {type: "string", default: null},
        TMESSAGES_Contact_name: {type: "string", default: null, optional:true},
        TMESSAGES_Contact_number: {type: "string", default: null, optional:true},
        TMESSAGES_Lat: {type: "string", default: null, optional:true},
        TMESSAGES_Long: {type: "string", default: null, optional:true},
        TMESSAGES_IS_Deel_Keyword: {type: "string", default: null, optional:true},
        TMESSAGES_IS_Dazz_id: {type: "string", default: null, optional:true},
        TMESSAGES_IS_Nynm_string: {type: "string", default: null, optional:true},
        TMESSAGES_IS_Nynm_short_string: {type: "string", default: null, optional:true},
        DC_USER_IMAGE: {type: "string", default: null},
        DN_PHONE_ONE: {type: "string", default: null, optional:true},
        name: {type: "string", default: null, optional:true},
        phone: {type: "string", default: null},
        DC_FIRST_NAME: {type: "string", default: null},
        DC_LAST_NAME: {type: "string", default: null},
  }
}

const ChatLogsData = {
    name: "chat_log_data",
    primarykey: "TChat_Log_Chat_Room_ID",
    properties: {
        TChat_Log_Chat_Room_ID: "int",
        Unread_msg_count: "int",
        TChat_Log_Is_userLeft: {type: "int", default: 0},
        TChat_Log_Is_Broadcast: {type: "int", default: 0},
        TChat_Log_Is_Mute: {type: "int", default: 0},
        TChat_Log_IS_Archive: {type: "int", default: 0},
        HCHAT_ROOM_Name: {type: "string", default: null},
        HCHAT_ROOM_IS_Group: {type: "int", default: 0},
        HCHAT_ROOM_Chat_Room_image: {type: "string", default: null, optional:true},
        HCHAT_ROOM_Description: {type: "string", default: null, optional:true},
        TMESSAGES_Content: { type: "string", default: null },
        TMESSAGES_Message_ID: {type: "int", default: null},
        TMESSAGES_UID: {type: "string", default: null},
        TMESSAGES_Read_Status: {type: "string", default: null},
        TMESSAGES_Today_First_message: {type: "int", default: 0},
        TMESSAGES_IS_User_Join: {type: "int", default: 0},
        TMESSAGES_UID: {type: "string", default: null},
        TChat_Log_Updated_On: {type: "date", default: null},
        TMESSAGES_File_Type: {type: "string", default: null},
        TMESSAGES_Reply_ID: {type: "int", default: 0, optional:true},
        DUSER_ROOM_UID: {type: "string", default: null},
        TMESSAGES_Reply_contand: {type: "string", default: null, optional:true},
        TMESSAGES_Contact_name: {type: "string", default: null, optional:true},
        TMESSAGES_Contact_number: {type: "string", default: null, optional:true},
        TMESSAGES_Lat: {type: "string", default: null, optional:true},
        TMESSAGES_Long: {type: "string", default: null, optional:true},
        TMESSAGES_IS_Nynm_short_string: {type: "string", default: null, optional:true},
        DUSER_ROOM_Role: {type: "string", default: null},
        DC_USER_IMAGE: {type: "string", default: null},
        DN_ID: {type: "string", default: null},
        DC_USERNAME: {type: "string", default: null},
        statusText: {type: "string", default: null},
        name: {type: "string", default: null, optional:true},
        phone: {type: "string", default: null},
        DC_FIRST_NAME: {type: "string", default: null},
        DC_LAST_NAME: {type: "string", default: null},
  }
}

export const DbSchemas = [
    ChatLogsData,
    chatRoomMessagesData,
];

